version: '2.1'

services:
  validator:
    image: hyperledger/sawtooth-validator:1.0
    container_name: validator
    volumes:
      - .:/pirate-talk
    expose:
      - 4004
    ports:
      - 4004:4004
    entrypoint: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen &&
          sawtooth keygen &&
          sawset genesis  -k /etc/sawtooth/keys/validator.priv &&
          sawset proposal create \
            -k /etc/sawtooth/keys/validator.priv \
            sawtooth.swa.administrators=$$(cat /root/.sawtooth/keys/root.pub) \
            -o config.batch &&
          sawadm genesis config-genesis.batch config.batch
        fi;
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
        "

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: rest-api
    expose:
      - 8008
    ports:
      - 8008:8008
    entrypoint: |
      sawtooth-rest-api -vv
        --connect tcp://validator:4004
        --bind rest-api:8008

  shell:
    image: hyperledger/sawtooth-shell:1.0
    container_name: shell
    entrypoint: |
      bash -c "
        if [ ! -f /root/.sawtooth/keys/root.priv ]; then
          sawtooth keygen
        fi;
        tail -f /dev/null
      "

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: settings-tp
    entrypoint: settings-tp -vv --connect tcp://validator:4004

  sabre-tp:
    image: sabre-tp
    container_name: sabre-tp
    build:
      context: ./sabre/tp
    volumes:
      - .:/pirate-talk
    entrypoint: |
      bash -c "
        cargo build &&
        sawtooth-sabre -vv -C tcp://validator:4004
      "

  sabre-cli:
    image: sabre-cli
    container_name: sabre-cli
    build:
      context: ./sabre/cli
    volumes:
      - .:/pirate-talk
      - ./keys:/root/.sawtooth/keys
    entrypoint: |
      bash -c "
        cargo build &&
        tail -f /dev/null
      "
